### ISSUE TITLE
Возвращать список изменений с сервера при возникновении конфликта

### ISSUE THREAD

**Issue by ikokostya** [yandex/datasync-js#10]
При возникновении конфликта (код 409) в ответе сервера возвращается список изменений.
Хочется иметь возможность получать эти изменения для разрешения конфлитков. Формат можно оставить таким, как отвечает сервер.

**Comment by twirl** [comment]
Ты хочешь полную дельту, или только конфликты?

**Comment by ikokostya** [comment]
Полную: все изменения между локальной и удаленной ревизиями.
