### ISSUE TITLE
Возможность указать свои vow и localforage

### ISSUE THREAD

**Issue by vitkarpov** [yandex/datasync-js#26]
Есть проект, который собирается **не** через ymodules. На проекте уже подключены `vow` и `localforage`. Подключая бандл `datasync-js` «как есть», мы получаем копии этих библиотек. Хотелось бы этого избежать. Как лучше быть?

Первое, что приходит в голову — может имеет смысл сделать АПИ, которое позволит сказать `datasync-js`, условно: принимай ссылки на `vow` и `localforage` снаружи + кастомный бандл без этих зависимостей?

**Comment by twirl** [comment]
Напишите свой gulpfile.js, см. как сделана stripped-сборка.

**Comment by vitkarpov** [comment]
👍
