### ISSUE TITLE
Событие Database#update происходит без обновления базы данных

### ISSUE THREAD

**Issue by ikokostya** [yandex/datasync-js#4]
Каждый вызов метода [Database#update()](https://tech.yandex.ru/datasync/jsapi/doc/ref/reference/cloud.dataSyncApi.Database-docpage/#update) вызывает событие `update`, даже если изменений на сервере не было.

Ожидаемое поведение: получать событие `update` только при появлении новых данных.

**Comment by ikokostya** [comment]
Или можно завести для этого случая новое событие `change`.

**Comment by twirl** [comment]
afe96b06b50e31372cac053898e59e099ffd3e71
